import { SavedTrip, TripPlannerInput, ItineraryDay } from '../types';

const STORAGE_KEY = 'tamizn_visa_saved_trips_v2';

/**
 * TAMIZN VISA - Offline & Saved Trips Storage Manager
 */
export const StorageService = {
  getSavedTrips(): SavedTrip[] {
    try {
      const data = localStorage.getItem(STORAGE_KEY);
      if (!data) return [];
      return JSON.parse(data);
    } catch {
      return [];
    }
  },

  saveTrip(
    name: string,
    input: TripPlannerInput,
    itineraryDays: ItineraryDay[],
    isOfflineSaved: boolean = true
  ): SavedTrip {
    const trips = this.getSavedTrips();
    const totalBudget = itineraryDays.reduce((sum, d) => sum + d.dayBudgetINR, 0);

    const newTrip: SavedTrip = {
      id: `trip-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      name: name || `${input.destinationDistrict} ${input.numberOfDays}-Day Exploration`,
      destinationDistrict: input.destinationDistrict,
      travelDate: input.travelDate || new Date().toISOString().split('T')[0],
      numberOfDays: input.numberOfDays,
      travelers: input.numberOfTravelers,
      travelerType: input.travelerType,
      budgetTotalINR: input.customBudgetINR || totalBudget * 1.25,
      budgetUsedINR: totalBudget,
      itineraryDays,
      createdAt: new Date().toISOString(),
      lastEditedAt: new Date().toISOString(),
      isOfflineSaved,
      notes: `Generated by TamizN Visa for ${input.travelerType} travel. Fully saved for offline reference.`,
    };

    trips.unshift(newTrip);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(trips));
    return newTrip;
  },

  updateTrip(id: string, updates: Partial<SavedTrip>): SavedTrip | null {
    const trips = this.getSavedTrips();
    const index = trips.findIndex((t) => t.id === id);
    if (index === -1) return null;

    trips[index] = {
      ...trips[index],
      ...updates,
      lastEditedAt: new Date().toISOString(),
    };

    localStorage.setItem(STORAGE_KEY, JSON.stringify(trips));
    return trips[index];
  },

  duplicateTrip(id: string): SavedTrip | null {
    const trips = this.getSavedTrips();
    const target = trips.find((t) => t.id === id);
    if (!target) return null;

    const duplicated: SavedTrip = {
      ...target,
      id: `trip-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      name: `${target.name} (Copy)`,
      createdAt: new Date().toISOString(),
      lastEditedAt: new Date().toISOString(),
    };

    trips.unshift(duplicated);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(trips));
    return duplicated;
  },

  deleteTrip(id: string): boolean {
    const trips = this.getSavedTrips();
    const filtered = trips.filter((t) => t.id === id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
    return true;
  },

  exportTripJson(trip: SavedTrip): void {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(trip, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${trip.name.replace(/[^a-zA-Z0-9]/g, '_')}_Offline_Dossier.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  },
};
